# This is a basic workflow to help you get started with Actions

name: Publish on Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: update submodules
      run: |
        git config --file=.gitmodules themes/meme https://github.com/reuixiy/hugo-theme-meme.git
        git config --file=.gitmodules public https://${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com/ravicini/ravicini.github.io.git
        git submodule sync
        git submodule update --init --recursive

    # Runs a single command using the runners shell
    - name: install hugo-extended
      run: sudo snap install hugo --channel=extended

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: ./deploy.sh