# This is a basic workflow to help you get started with Actions

name: Publish on Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: install hugo-extended
      run: sudo snap install hugo --channel=extended
    
    - name: build site
      run: hugo -t meme
    
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        external_repository: ravicini/ravicini.github.io
        publish_dir: ./public
        publish_branch: master
