# This is a basic workflow to help you get started with Actions

name: Publish on Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: install hugo-extended
      run: sudo snap install hugo --channel=extended
    
    - name: build site
      run: hugo -t meme
    
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    # - name: init name and add changes
    #   run: |
    #     cd public
    #     git config --local user.email "marco@ravicini.ch"
    #     git config --local user.name "Marco Ravicini"
    #     git add .
    #     git commit -m "published $(date)" -a
    #     git remote set-url origin https://$USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/ravicini/ravicini.github.io.git
    #     git push origin master
